In [1]:
!pip install numpy as np

ERROR: Could not find a version that satisfies the requirement as (from versions: none)
ERROR: No matching distribution found for as


In [2]:
import numpy as np

In [3]:
l = [54,41,58]

In [4]:
type(l)

list

In [5]:
np.array(l)

array([54, 41, 58])

In [6]:
type(np.array(l))

numpy.ndarray

In [7]:
l = [[54,41],[34,84],[101,5441]]

In [8]:
np.array(l)

array([[  54,   41],
       [  34,   84],
       [ 101, 5441]])

In [9]:
np.empty([3,2])

array([[-6.95308211e-310, -1.32635771e-148],
       [ 1.03144477e-311,  1.03144477e-311],
       [ 1.13635099e-322,  1.72922976e-322]])

In [10]:
np.zeros([4,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros([2,3],dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.ones([3,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [14]:
l = [['p','i','y','u'],['y','a','s','h']]

In [15]:
np.array(l)

array([['p', 'i', 'y', 'u'],
       ['y', 'a', 's', 'h']], dtype='<U1')

In [16]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
np.arange(2,12,3)

array([ 2,  5,  8, 11])

In [18]:
np.linspace(2,17,5)

array([ 2.  ,  5.75,  9.5 , 13.25, 17.  ])

In [19]:
np.linspace(2,17)

array([ 2.        ,  2.30612245,  2.6122449 ,  2.91836735,  3.2244898 ,
        3.53061224,  3.83673469,  4.14285714,  4.44897959,  4.75510204,
        5.06122449,  5.36734694,  5.67346939,  5.97959184,  6.28571429,
        6.59183673,  6.89795918,  7.20408163,  7.51020408,  7.81632653,
        8.12244898,  8.42857143,  8.73469388,  9.04081633,  9.34693878,
        9.65306122,  9.95918367, 10.26530612, 10.57142857, 10.87755102,
       11.18367347, 11.48979592, 11.79591837, 12.10204082, 12.40816327,
       12.71428571, 13.02040816, 13.32653061, 13.63265306, 13.93877551,
       14.24489796, 14.55102041, 14.85714286, 15.16326531, 15.46938776,
       15.7755102 , 16.08163265, 16.3877551 , 16.69387755, 17.        ])

In [20]:
arr = np.array(10)
arr.ndim

0

In [21]:
arr = np.array([54,41])
arr.ndim

1

In [22]:
arr = np.array([[101,34],[84,110]])
arr,arr.ndim

(array([[101,  34],
        [ 84, 110]]),
 2)

In [23]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr,arr.ndim

(array([[[1, 2],
         [3, 4]],
 
        [[5, 6],
         [7, 8]]]),
 3)

In [24]:
arr.shape

(2, 2, 2)

In [25]:
arr = np.array([[[[[54,41,101,34,84]]]]])
arr.ndim

5

In [26]:
arr = np.array([54,41,101,34,84],ndmin=4)
arr

array([[[[ 54,  41, 101,  34,  84]]]])

In [27]:
arr = np.array([[54,41],[34,84]],ndmin=3)
arr

array([[[54, 41],
        [34, 84]]])

In [28]:
arr = np.array([[54,41],[34,84]])
arr

array([[54, 41],
       [34, 84]])

In [29]:
np.random.rand(6)*100

array([ 9.67686595, 81.28042912,  3.31866334, 84.19777291, 28.12457017,
       50.97650833])

In [30]:
np.random.rand(2,3)*100

array([[17.78872657, 73.38829619, 40.96294551],
       [77.6074381 , 86.493356  , 95.87176377]])

In [31]:
np.random.randint(6)

5

In [32]:
np.random.randint(6,size=[3,2])

array([[5, 5],
       [2, 2],
       [2, 3]], dtype=int32)

In [33]:
np.random.choice(["head","tails"])

np.str_('head')

In [34]:
np.random.choice([1,2,3,4,5,6])

np.int64(6)

In [35]:
np.random.randint(100,size=(10,3))

array([[23, 25, 36],
       [27, 94, 20],
       [40,  6, 62],
       [22, 19, 28],
       [51, 23, 80],
       [ 2, 30, 90],
       [96, 45, 90],
       [53, 71, 64],
       [89, 58, 32],
       [40, 71,  1]], dtype=int32)

In [36]:
import pandas as pd

In [37]:
pd.DataFrame(np.random.randint(100,size=(10,3)),columns=["a","b","c"])

,a,b,c
0,57,19,97
1,23,35,10
2,35,73,71
3,30,99,0
4,7,4,15
5,4,0,74
6,37,50,48
7,90,95,52
8,46,23,47
9,34,95,23


In [38]:
arr = np.array([1,2,3,4])
print(arr.dtype)

int64


In [39]:
type(arr)

numpy.ndarray

In [40]:
arr = np.array(["priyanka","yash","piyu","nishit"])
arr.dtype

dtype('<U8')

In [41]:
type(arr)

numpy.ndarray

In [42]:
arr = np.array([54.41,34.84,101.110])
new_arr = arr.astype('i')

In [43]:
new_arr

array([ 54,  34, 101], dtype=int32)

In [44]:
arr = np.array([54.41,34.84,101.110])
new_arr = arr.astype('S')
new_arr

array([b'54.41', b'34.84', b'101.11'], dtype='|S32')

In [45]:
arr = np.array([54,41,34])
arr.astype("f")

array([54., 41., 34.], dtype=float32)

In [46]:
arr = np.array([5,0,4,0.001,0.0,0.00000000001,41])
arr.dtype

dtype('float64')

In [47]:
new_arr = arr.astype("b")
new_arr

array([ 5,  0,  4,  0,  0,  0, 41], dtype=int8)

In [48]:
new_arr = arr.astype(bool)
new_arr

array([ True, False,  True,  True, False,  True,  True])

In [49]:
arr = np.array([10,20,30])
copy_arr = arr.copy()
view_arr = arr.view()

In [50]:
print(arr)
print(copy_arr)
print(view_arr)

[10 20 30]
[10 20 30]
[10 20 30]


In [51]:
arr[0] = 100
copy_arr[2] = 300
view_arr[1] = 200

In [52]:
print(arr)
print(copy_arr)
print(view_arr)

[100 200  30]
[ 10  20 300]
[100 200  30]


In [53]:
arr = np.array(["aBc","xYz","pQr"])

In [54]:
np.char.lower(arr)

array(['abc', 'xyz', 'pqr'], dtype='<U3')

In [55]:
np.char.upper(arr)

array(['ABC', 'XYZ', 'PQR'], dtype='<U3')