In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])

In [3]:
arr[2],arr[-2]

(np.int64(3), np.int64(4))

In [4]:
arr[1:4]

array([2, 3, 4])

In [5]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [6]:
arr[1,2],arr[-1,-1],arr[2,-2]

(np.int64(7), np.int64(12), np.int64(11))

In [7]:
arr[0:2,1:2]

array([[2],
       [6]])

In [8]:
arr[-3:-1,-4:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [9]:
arr = np.array(10)
arr.shape

()

In [10]:
arr = np.array([1,2,3,4,5,6,7])
arr.shape

(7,)

In [11]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr.shape

(2, 5)

In [12]:
arr = np.array([[[[1,2,3,4,5],[6,7,8,9,10]]]])
arr.shape

(1, 1, 2, 5)

In [13]:
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])
arr.shape

(3, 2, 3)

In [14]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [15]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18


In [16]:
arr = np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [17]:
arr = np.array([[[[1,2,3,4,5],[6,7,8,9,10]]]])
arr.shape

(1, 1, 2, 5)

In [18]:
arr = arr.reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
for i in arr:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [20]:
for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [21]:
arr = [[54,41,34],[34,84,101]]
type(arr)

list

In [22]:
arr = np.array([[54,41,34],[34,84,101]])
type(arr),arr

(numpy.ndarray,
 array([[ 54,  41,  34],
        [ 34,  84, 101]]))

In [23]:
arr.T

array([[ 54,  34],
       [ 41,  84],
       [ 34, 101]])

In [24]:
arr = np.array([2.25748,3.68923,5.7843,9.29,8.500000000000001,7.5,6.5])

In [25]:
np.around(arr)

array([2., 4., 6., 9., 9., 8., 6.])

In [26]:
np.around(arr,decimals=2)

array([2.26, 3.69, 5.78, 9.29, 8.5 , 7.5 , 6.5 ])

In [27]:
np.around([5.5,6.5,7.5,8.5])

array([6., 6., 8., 8.])

In [28]:
np.floor(arr)

array([2., 3., 5., 9., 8., 7., 6.])

In [29]:
np.ceil(arr)

array([ 3.,  4.,  6., 10.,  9.,  8.,  7.])

In [30]:
np.array([10,20],dtype="float")

array([10., 20.])

In [31]:
arr1 = np.array([54,41,58])
arr2 = np.array([34,84,101])

In [32]:
np.add(arr1,arr2)

array([ 88, 125, 159])

In [33]:
np.subtract(arr1,arr2)

array([ 20, -43, -43])

In [34]:
np.multiply(arr1,arr2)

array([1836, 3444, 5858])

In [35]:
np.divide(arr1,arr2)

array([1.58823529, 0.48809524, 0.57425743])

In [36]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [37]:
arr = np.array([1,2,3,4,5,6])

In [38]:
np.median(arr)

np.float64(3.5)

In [39]:
np.mean(arr)

np.float64(3.5)

In [40]:
np.average(arr)

np.float64(3.5)

In [41]:
np.var(arr)

np.float64(2.9166666666666665)

In [42]:
np.std(arr)

np.float64(1.707825127659933)

In [43]:
np.sqrt(2.9166666666666665),np.sqrt(np.var(arr))

(np.float64(1.707825127659933), np.float64(1.707825127659933))

In [44]:
arr = np.array([[20,10],[3,7],[5,8],[9,3]])

In [45]:
np.sort(arr,axis=1) # bydefault

array([[10, 20],
       [ 3,  7],
       [ 5,  8],
       [ 3,  9]])

In [46]:
np.sort(arr,axis=0)

array([[ 3,  3],
       [ 5,  7],
       [ 9,  8],
       [20, 10]])

In [47]:
np.sort(np.sort(arr,axis=0))

array([[ 3,  3],
       [ 5,  7],
       [ 8,  9],
       [10, 20]])

In [48]:
arr = np.array([2,2,5,6,6,8,9,2])

In [49]:
np.where(arr == 2)

(array([0, 1, 7]),)

In [50]:
np.where(arr == 6)

(array([3, 4]),)

In [51]:
arr = np.array([[2,3],[4,2],[3,5],[2,5]])
arr

array([[2, 3],
       [4, 2],
       [3, 5],
       [2, 5]])

In [52]:
np.where(arr == 2)

(array([0, 1, 3]), array([0, 1, 0]))

In [53]:
np.where(arr == 3)

(array([0, 2]), array([1, 0]))

In [54]:
np.where(arr == 4)

(array([1]), array([0]))

In [55]:
np.where(arr == 5)

(array([2, 3]), array([1, 1]))

In [56]:
arr = np.array([1,2,3,4,5,6])
np.array_split(arr,3),np.array_split(arr,2)

([array([1, 2]), array([3, 4]), array([5, 6])],
 [array([1, 2, 3]), array([4, 5, 6])])

In [57]:
arr = np.array([1,2,3,4,5,6,7])
np.array_split(arr,3),np.array_split(arr,2)

([array([1, 2, 3]), array([4, 5]), array([6, 7])],
 [array([1, 2, 3, 4]), array([5, 6, 7])])

In [58]:
np.array_split(np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]),2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[10, 11, 12],
        [13, 14, 15]])]

In [59]:
arr1 = np.array([1,2,3,54])
arr2 = np.array([4,5,6])

In [60]:
np.concatenate([arr1,arr2])

array([ 1,  2,  3, 54,  4,  5,  6])

In [61]:
np.concatenate([arr1,arr2],axis=0)

array([ 1,  2,  3, 54,  4,  5,  6])

In [62]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

In [63]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [64]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])